# SDK equivalent of configuring and submitting an evaluation in Foundry.
# Register evaluators, define one evaluation, then start one run.
# Foundry calls the deployed agent and scores its answers; this file does neither locally.
# CLI options and saved evidence files are demo conveniences, not Foundry requirements.

import argparse
import hashlib
import json
import os
import shutil
from pathlib import Path
from uuid import uuid4

import yaml
from azure.ai.projects import AIProjectClient
from azure.identity import DefaultAzureCredential
from openai import OpenAI

from agent.tools import REFERENCE_DATE

ROOT = Path(__file__).parent


def prepare_requests(
    dataset: Path,
    agent_version: str,
    judge_model: str,
    *,
    smoke: bool = False,
) -> dict:
    # Build request bodies locally. Nothing in this function submits a cloud job.
    rows = [json.loads(line) for line in dataset.read_text().splitlines() if line.strip()]
    if smoke:
        if dataset.stem == "golden-holdout":
            raise ValueError("Keep the release set intact; do not smoke-test it.")
        smoke_cases = {
            "clarify_desks",
            "remaining_designcloud_security",
            "exception_nova_spending",
            "ready_keyboards",
        }
        rows = [row for row in rows if row["name"] in smoke_cases]
        if len(rows) != len(smoke_cases):
            raise ValueError("The smoke dataset must contain the representative cases.")
    evaluator = json.loads((ROOT / "evaluators/purchasing-next-action.json").read_text())
    split = "release" if dataset.stem == "golden-holdout" else "development"
    # 2. Evaluation definition: choose the evaluators and connect their inputs.
    # Creating this definition does not yet invoke the purchasing agent.
    evaluation = {
        "name": f"purchasing-next-action-evaluation-{split}" + ("-smoke" if smoke else ""),
        "data_source_config": {
            "type": "custom",
            "item_schema": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "query": {"type": "string"},
                    "ground_truth": {"type": "string"},
                },
                "required": ["name", "query", "ground_truth"],
                "additionalProperties": False,
            },
            "include_sample_schema": True,
        },
        "testing_criteria": [
            {
                "type": "azure_ai_evaluator",
                "name": "next_action_success",
                "evaluator_name": evaluator["name"],
                "initialization_parameters": {
                    "deployment_name": judge_model,
                    "threshold": 1,
                },
                # item.* comes from our dataset; sample.* is generated by the real agent.
                # Compare the reference answer with actual output, never with itself.
                "data_mapping": {
                    "query": "{{item.query}}",
                    "ground_truth": "{{item.ground_truth}}",
                    "response": "{{sample.output_text}}",
                },
            },
        ],
    }
    # 3. Run request: provide the cases and select the deployed agent version.
    # "azure_ai_target_completions" tells Foundry to generate and then score responses.
    run = {
        "name": evaluation["name"],
        "metadata": {
            "reference_date": REFERENCE_DATE.isoformat(),
            "agent_version": agent_version,
            "dataset_split": split,
        },
        "data_source": {
            "type": "azure_ai_target_completions",
            "source": {
                "type": "file_content",
                "content": [
                    {
                        "item": {
                            "name": row["name"],
                            "query": row["query"],
                            "ground_truth": row["ground_truth"],
                        }
                    }
                    for row in rows
                ],
            },
            # Only the question reaches the agent, never the expected answer.
            "input_messages": {
                "type": "template",
                "template": [
                    {
                        "type": "message",
                        "role": "user",
                        "content": {"type": "input_text", "text": "{{item.query}}"},
                    }
                ],
            },
            # Evaluate the real hosted agent, not a direct call to its underlying model.
            "target": {
                "type": "azure_ai_agent",
                "name": "purchasing-advice-demo",
                "version": agent_version,
            },
        },
    }
    return {"evaluator": evaluator, "evaluation": evaluation, "run": run}


def prepare_optimizer(project: AIProjectClient, requests: dict) -> dict:
    config = yaml.safe_load((ROOT / "optimize-next-action.yaml").read_text())
    if (
        requests["run"].get("metadata", {}).get("dataset_split") != "development"
        or len(requests["evaluation"]["testing_criteria"]) != 1
        or requests["run"]["name"].endswith("-smoke")
    ):
        raise ValueError("Next-action optimisation requires the full development set only.")
    if [entry["name"] for entry in config["evaluators"]] != [requests["evaluator"]["name"]]:
        raise ValueError("Evaluator mismatch: optimisation requires the single next-action judge.")
    items = [entry["item"] for entry in requests["run"]["data_source"]["source"]["content"]]
    validation_items = [
        json.loads(line)
        for line in (ROOT / config["validation_dataset"]["local_uri"]).read_text().splitlines()
        if line.strip()
    ]
    if not validation_items or any(
        set(item) != {"name", "query", "ground_truth"}
        or any(not isinstance(value, str) or not value.strip() for value in item.values())
        for item in validation_items
    ):
        raise ValueError("Holdout validation requires nonempty names, questions and references.")
    for field in ("name", "query"):
        values = [item[field] for item in validation_items]
        if len(set(values)) != len(values) or set(values) & {item[field] for item in items}:
            raise ValueError(
                "Holdout names and questions must be unique and disjoint from training."
            )
    directory = ROOT / "evidence" / f"next-action-optimisation-{uuid4().hex}"
    directory.mkdir(parents=True, exist_ok=True)
    baseline = ROOT / config["agent"]["config"]
    shutil.copytree(baseline.parent, directory / "baseline")
    baseline = directory / "baseline" / baseline.name
    dataset = directory / "golden-development.jsonl"
    dataset.write_text("".join(json.dumps(item) + "\n" for item in items))
    validation_dataset = directory / "golden-holdout.jsonl"
    validation_dataset.write_text("".join(json.dumps(item) + "\n" for item in validation_items))
    config["dataset"]["local_uri"] = str(dataset.resolve())
    config["validation_dataset"]["local_uri"] = str(validation_dataset.resolve())
    evaluator = project.beta.evaluators.create_version(
        name=requests["evaluator"]["name"], evaluator_version=requests["evaluator"]
    )
    config["agent"]["config"] = str(baseline.resolve())
    config["agent"]["version"] = requests["run"]["data_source"]["target"]["version"]
    config["evaluators"][0]["version"] = evaluator.version
    config["evaluators"][0]["initialization_parameters"] = requests["evaluation"][
        "testing_criteria"
    ][0]["initialization_parameters"]
    config["options"]["eval_model"] = config["evaluators"][0]["initialization_parameters"][
        "deployment_name"
    ]
    path = directory / "optimize-prepared.yaml"
    path.write_text(yaml.safe_dump(config, sort_keys=False))
    print(
        f"Prepared {len(items)} training and {len(validation_items)} holdout validation cases; "
        f"judge version {evaluator.version}."
    )
    print(f"Optimizer settings: {path}")
    print("No optimisation job submitted.")
    print(f"azd ai agent optimize --config '{path}' -e ai-genius-hosted")
    return {
        "config": config,
        "dataset": items,
        "validation_dataset": validation_items,
        "reference_date": REFERENCE_DATE.isoformat(),
    }


def show_results(client: OpenAI, eval_id: str, run_id: str) -> dict:
    # Read the service's original JSON: the OpenAI run model doesn't yet describe
    # all Azure target fields, and azd's current reader rejects structured messages.
    response = client.evals.runs.with_raw_response.retrieve(run_id, eval_id=eval_id)
    run = response.http_response.json()
    items = [
        item.model_dump(mode="json")
        for item in client.evals.runs.output_items.list(run_id=run_id, eval_id=eval_id)
    ]
    evaluation = client.evals.with_raw_response.retrieve(eval_id).http_response.json()
    report = {"evaluation": evaluation, "run": run, "items": items}
    evidence = ROOT / "evidence" / f"{run_id}.json"
    evidence.parent.mkdir(exist_ok=True)
    evidence.write_text(json.dumps(report, indent=2))
    print(f"Status: {run['status']}")
    print(f"Results: {json.dumps(run['result_counts'])}")
    if run.get("error"):
        print(f"Error: {json.dumps(run['error'])}")
    print(f"Saved full answers, scores and explanations: {evidence}")
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description="Submit a native Foundry evaluation (billable).")
    operation = parser.add_mutually_exclusive_group()
    operation.add_argument(
        "--release", action="store_true", help="Use the 12 held-out release cases."
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Save request bodies locally; no cloud operations."
    )
    parser.add_argument("--agent-version", default="1", help="Pinned deployed agent version.")
    parser.add_argument(
        "--judge-model", default="gpt-5.5", help="Next-action judge model deployment."
    )
    parser.add_argument(
        "--smoke",
        action="store_true",
        help="Run four representative development cases.",
    )
    operation.add_argument(
        "--prepare-optimizer",
        action="store_true",
        help="Prepare expected answers and register the prompt judge; no optimisation submitted.",
    )
    operation.add_argument(
        "--show", nargs=2, metavar=("EVAL_ID", "RUN_ID"), help="Read results; never starts a run."
    )
    args = parser.parse_args()
    if args.smoke and (args.release or args.prepare_optimizer or args.show):
        parser.error("--smoke is only available for a development evaluation")
    if args.dry_run and args.show:
        parser.error("--dry-run cannot be combined with a read-only result operation")
    if args.show:
        with (
            DefaultAzureCredential() as credential,
            AIProjectClient(
                endpoint=os.environ["FOUNDRY_PROJECT_ENDPOINT"], credential=credential
            ) as project,
            project.get_openai_client() as client,
        ):
            show_results(client, eval_id=args.show[0], run_id=args.show[1])
        return
    directory = ROOT / "agent/datasets/next-action"
    dataset = directory / ("golden-holdout.jsonl" if args.release else "golden-development.jsonl")
    requests = prepare_requests(
        dataset,
        args.agent_version,
        args.judge_model,
        smoke=args.smoke,
    )
    requests["source_sha256"] = {
        str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest()
        for pattern in ("*.py", "requirements.txt", "data/*", ".agent_configs/baseline/*")
        for path in (ROOT / "agent").glob(pattern)
        if path.is_file()
    }
    # Our local audit trail: preserve inputs before submission and IDs after each step.
    # This is useful for the demo but is not part of Foundry's scoring implementation.
    evidence = ROOT / "evidence" / f"evaluation-{uuid4().hex}.json"
    evidence.parent.mkdir(exist_ok=True)
    evidence.write_text(json.dumps(requests, indent=2))
    print(f"Submission snapshot: {evidence}", flush=True)
    if args.dry_run:
        print("Dry run only: no registration, evaluation or optimisation submitted.")
        return
    endpoint = os.environ["FOUNDRY_PROJECT_ENDPOINT"]
    requests["project_endpoint"] = endpoint
    evidence.write_text(json.dumps(requests, indent=2))

    # Cloud operations begin here. Despite its name, get_openai_client() below connects
    # to this Foundry project's OpenAI-compatible API, not the public OpenAI service.
    with (
        DefaultAzureCredential() as credential,
        AIProjectClient(endpoint=endpoint, credential=credential) as project,
        project.get_openai_client() as client,
    ):
        if args.prepare_optimizer:
            requests["optimizer"] = prepare_optimizer(project, requests)
            evidence.write_text(json.dumps(requests, indent=2))
            return
        evaluator = project.beta.evaluators.create_version(
            name=requests["evaluator"]["name"], evaluator_version=requests["evaluator"]
        )
        requests["evaluation"]["testing_criteria"][0]["evaluator_version"] = evaluator.version
        evidence.write_text(json.dumps(requests, indent=2))
        # Store the evaluation definition in Foundry; no agent answers are generated yet.
        evaluation = client.evals.create(
            name=requests["evaluation"]["name"],
            data_source_config=requests["evaluation"]["data_source_config"],
            testing_criteria=requests["evaluation"]["testing_criteria"],
        )
        requests["eval_id"] = evaluation.id
        evidence.write_text(json.dumps(requests, indent=2))
        print(f"Eval ID: {evaluation.id}", flush=True)
        # Start the billable cloud run: Foundry calls the agent for each question and judges it.
        run = client.evals.runs.create(
            eval_id=evaluation.id,
            name=requests["run"]["name"],
            metadata=requests["run"]["metadata"],
            data_source=requests["run"]["data_source"],
        )
        requests["run_id"] = run.id
        evidence.write_text(json.dumps(requests, indent=2))
        # Submission is not completion. Use the report/command to inspect progress and results.
        print(f"Run ID: {run.id}")
        if run.report_url:
            print(f"Report: {run.report_url}")
        print(f"uv run --frozen python evaluate.py --show {evaluation.id} {run.id}")


if __name__ == "__main__":
    main()
